# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloadMusicUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout.addWidget(self.searchEdit)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filePathEdit = QtWidgets.QLabel(self.centralwidget)
        self.filePathEdit.setText("")
        self.filePathEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filePathEdit.setObjectName("filePathEdit")
        self.horizontalLayout_2.addWidget(self.filePathEdit)
        self.selectPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectPathButton.setMinimumSize(QtCore.QSize(80, 23))
        self.selectPathButton.setMaximumSize(QtCore.QSize(80, 23))
        self.selectPathButton.setObjectName("selectPathButton")
        self.horizontalLayout_2.addWidget(self.selectPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.downResultLable = QtWidgets.QLabel(self.centralwidget)
        self.downResultLable.setText("")
        self.downResultLable.setAlignment(QtCore.Qt.AlignCenter)
        self.downResultLable.setObjectName("downResultLable")
        self.verticalLayout.addWidget(self.downResultLable)
        self.resultWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.resultWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.resultWidget.setObjectName("resultWidget")
        self.resultWidget.setColumnCount(4)
        self.resultWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultWidget.setItem(0, 3, item)
        self.verticalLayout.addWidget(self.resultWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1292, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionpath = QtWidgets.QAction(MainWindow)
        self.actionpath.setObjectName("actionpath")
        self.actionauthour = QtWidgets.QAction(MainWindow)
        self.actionauthour.setObjectName("actionauthour")
        self.actionauthor = QtWidgets.QAction(MainWindow)
        self.actionauthor.setObjectName("actionauthor")
        self.menu.addAction(self.actionauthor)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchButton.setText(_translate("MainWindow", "搜索"))
        self.selectPathButton.setText(_translate("MainWindow", "选择下载目录"))
        item = self.resultWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.resultWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.resultWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "专辑名"))
        item = self.resultWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "时长"))
        __sortingEnabled = self.resultWidget.isSortingEnabled()
        self.resultWidget.setSortingEnabled(False)
        self.resultWidget.setSortingEnabled(__sortingEnabled)
        self.menu.setTitle(_translate("MainWindow", "about"))
        self.actionpath.setText(_translate("MainWindow", "downloadFilePath"))
        self.actionauthour.setText(_translate("MainWindow", "authour"))
        self.actionauthor.setText(_translate("MainWindow", "author"))
